### ISSUE TITLE
Support testnet and regtest

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-compose#13]
Testnet and regtest modes would really help to quickly set up and try out new clean installations for development and testing purposes.

**Comment by nolim1t** [comment]
already working on testnet

**Comment by mayankchhabra** [comment]
Yes. We just need a way to quickly shift between testnet/regtest/mainnet.

**Comment by nolim1t** [comment]
I'm working on a testnet solution first... and with luck adding the other should be easy enough

**Comment by nolim1t** [comment]
By quickly.. I mean scripting it.

And because we have PWD support over HOME we can already just have different folders for different things ;)

**Comment by nolim1t** [comment]
![regtest](https://user-images.githubusercontent.com/83470/85527330-fa2c8e00-b634-11ea-894d-984d5bcfc8d0.png)
