### ISSUE TITLE
Move and test services out without host networking

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel-compose#26]
For security purposes Move and test services out without host networking.

Only services which should have external access are:

* bitcoind port 8333
* lnd port 9735
* nginx port 80

What needs to happen:

- [x] LND v0.10.0 upgraded
- [x] Tor container
- [x] Generate tor passwords and write to lnd config file

**Comment by nolim1t** [comment]
Done with this.. Just testing things out now

**Comment by mayankchhabra** [comment]
Hey @nolim1t can we merge this now?

**Comment by nolim1t** [comment]
Yes I think we can there are no issues at the moment with the host networkingOn Sat, Jul 4, 2020 at 17:12, Mayank Chhabra <notifications@github.com> wrote:  
Hey @nolim1t can we merge this now?
